### ISSUE TITLE
If importing all modules from Bootstrap 5, do so like this:

### ISSUE THREAD

**Issue by Mordef** [trvswgnr/bs5-lightbox#18] opened 2022-05-04 05:08 UTC
```
import * as bootstrap from 'bootstrap'
import 'bs5-lightbox'
```

Results in
```
ERROR in [at-loader] ./node_modules/bs5-lightbox/dist/index.d.ts:14:19
    TS2503: Cannot find namespace 'bootstrap'.

ERROR in [at-loader] ./node_modules/bs5-lightbox/dist/index.d.ts:15:22
    TS2503: Cannot find namespace 'bootstrap'.

ERROR in [at-loader] ./node_modules/bs5-lightbox/dist/index.d.ts:18:12
    TS2503: Cannot find namespace 'bootstrap'.

ERROR in [at-loader] ./node_modules/bs5-lightbox/dist/index.d.ts:19:15
    TS2503: Cannot find namespace 'bootstrap'.

ERROR in [at-loader] ./node_modules/bs5-lightbox/dist/index.d.ts:39:31
    TS2503: Cannot find namespace 'bootstrap'.

ERROR in [at-loader] ./node_modules/bs5-lightbox/dist/index.d.ts:39:56
    TS2503: Cannot find namespace 'bootstrap'.
```

Same with
```
import { Modal, Carousel, Collapse, Dropdown, Offcanvas } from 'bootstrap';
import 'bs5-lightbox'
```

**Comment by trvswgnr** [comment] 2022-05-04 12:29
Duplicate of #17

**Closed** 2022-05-04 12:29 UTC
Labels: duplicate
