### ISSUE TITLE
console error - png bug

### ISSUE THREAD

**Issue by pfpro** [trvswgnr/bs5-lightbox#4] opened 2021-11-14 17:22 UTC
Hi there,

are there any restrictions to PNG format?

i get error message in console:

=== CHROME
(index):1 Uncaught TypeError: Cannot read properties of undefined (reading 'previousSibling')
    at HTMLImageElement.onload ((index):1)

=== FIREFOX
Uncaught TypeError: this.add is undefined

when i use JPG file everything works fine ...

**Comment by pfpro** [comment] 2022-02-07 15:54
thank you.

although I now believe that it has nothing to do with the file type.
the error described occurs when i use the "gallery feature".

**Comment by Rafael-Esteves** [comment] 2022-02-10 21:45
This error seems to be caused by line 97:
`onload += /\.png/.test(src) ? `this.add.previousSibling.remove()` : '';`

I just commented it out and the error is gone. 
No idea what this line was doing tho

**Comment by trvswgnr** [comment] 2022-03-23 06:43
This has been resolved in [v1.7.10](https://github.com/trvswgnr/bs5-lightbox/releases/tag/v1.7.10)

**Closed** 2022-03-30 07:29 UTC
Labels: bug, done
